version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "info", "stats"]
      interval: 15s
      timeout: 1s
      retries: 3

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z -v 0.0.0.0 2181
      interval: 15s
      timeout: 1s
      retries: 3

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: kafka
      # KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    volumes:
      - kafka_data:/kafka
    healthcheck:
      test: nc -z -v 0.0.0.0 9092
      interval: 15s
      timeout: 1s
      retries: 3

volumes:
  redis_data:
  kafka_data: